#pragma once
enum status_codes {
  STATUS_SUCCESS = 200,
  STATUS_FAILED = 202,
  STATUS_HOST_REQUEST = 100,
  STATUS_DEVICE_INFO = 101,
  STATUS_INTERNAL_FUNCTION = 102,
  STATUS_INITIAL_DEVICE = 203,
  STATUS_TO_HOSTS = 204, 
  STATUS_SENSOR = 205 
};